# Generated by Django 2.2.2 on 2019-07-01 07:21

import constrainedfilefield.fields.file
from django.db import migrations, models
import document_catalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=('text/plain', 'application/pdf', 'image/png', 'image/jpg', 'image/jpeg'), max_length=200, max_upload_size=10485760, mime_lookup_length=4096, upload_to=document_catalogue.models.document_upload_path_callback),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
